[tools]
bat = "0.26.1"
cmake = "4.2.3"
codex = "0.104.0"
fd = "10.3.0"
fzf = "0.67.0"
lazydocker = "0.24.4"
lazygit = "0.59.0"
lua = "5.5.0"
neovim = "0.11.6"
node = "25.6.1"
ripgrep = "15.1.0"
starship = "1.24.2"
tmux = "3.6a"
tree-sitter = "0.26.5"
yazi = "26.1.22"
